# define variables
CC = gcc
CFLAGS= -Wall -g

all: vmtest print_address func_ptr auto buffer_overflow tiny_printf permutation vla2
vmtest: vmtest.c
print_address: print_address.c
func_ptr: func_ptr.c
auto: auto.c
buffer_overflow: buffer_overflow.c
tiny_printf: tiny_printf.c
permutation: permutation.c
vla2: vla2.c

clean:
	rm -f vmtest print_address func_ptr auto tiny_printf permutation vla2
