# define variables
CC = gcc
CFLAGS= -Wall -g

all: integerpromotion designated_initializer compound_literal.c

integerpromotion: integerpromotion.c
designated_initializer: designated_initializer.c
compound_literal: compound_literal.c

clean:
	rm -f integerpromotion designated_initializer compound_literal
