# define variables
CC = gcc
CFLAGS= -Wall -g

all: test12 test13 test14 test15 extra_credit15 extra_credit15_function extra_credit15_while extra_credit15_all_array extra_credit15_all_pointer break_ex16 extra_credit16

test12: test12.c
test13: test13.c
test14: test14.c
test15: test15.c
extra_credit15: extra_credit15.c
extra_credit15_function: extra_credit15_function.c
extra_credit15_while: extra_credit15_while.c
extra_credit15_all_array: extra_credit15_all_array.c
extra_credit15_all_pointer: extra_credit15_all_pointer.c
break_ex16: break_ex16.c
extra_credit16: extra_credit16.c

clean:
	rm -f test12 test13 test14 test15 extra_credit15 extra_credit15_function extra_credit15_while extra_credit15_all_array extra_credit15_all_pointer break_ex16 extra_credit16
