# define variables
CC = gcc
CFLAGS= -Wall -g

test12: test12.c
test13: test13.c
test14: test14.c
test15: test15.c
extra_credit15: extra_credit15.c
extra_credit15_function: extra_credit15_function.c
extra_credit15_while: extra_credit15_while.c
extra_credit15_all_array: extra_credit15_all_array.c
extra_credit15_all_pointer: extra_credit15_all_pointer.c
break_ex16: break_ex16.c
extra_credit16: extra_credit16.c
break_ex17: break_ex17.c my_strncpy.h my_strncpy.c
my_strncpy_test: my_strncpy_test.c my_strncpy.c my_strncpy.h
extra_credit17: extra_credit17.c my_strncpy.c my_strncpy.h
extra_credit17_dynamic: extra_credit17_dynamic.c my_strncpy.c my_strncpy.h
extra_credit17_anotherAddress: extra_credit17_anotherAddress.c my_strncpy.c my_strncpy.h
extra_credit17_global: extra_credit17_global.c my_strncpy.c my_strncpy.h
extra_credit17_stack: extra_credit17_stack.c
extra_credit17_stack2: extra_credit17_stack2.c
break_ex18: break_ex18.c
extra_credit18: extra_credit18.c


clean:
	rm -f test12 test13 test14 test15 extra_credit15 extra_credit15_function extra_credit15_while extra_credit15_all_array extra_credit15_all_pointer break_ex16 extra_credit16 break_ex17 my_strncpy_test extra_credit17 extra_credit17_dynamic extra_credit17_anotherAddress extra_credit17_global extra_credit17_stack extra_credit17_stack2 break_ex18 extra_credit18
