# define variables
CC = gcc
CFLAGS= -Wall -g

all: pointer pointer_calc get_xy array array2 myGet_word myVla
pointer: pointer.c
pointer_calc: pointer_calc.c
get_xy: get_xy.c
array: array.c
array2: array2.c
myGet_word: myGet_word.c  
myVla: myVla.c
clean:
	rm -f pointer pointer_calc get_xy array array2 myGet_word myVla
