# define variables
CC = gcc
CFLAGS= -Wall -g

all: output_argument pass_array variable_array realloc

output_argument: output_argument.c
pass_array: pass_array.c
variable_array: variable_array.c
realloc: realloc.c

clean:
	rm -f output_argument pass_array variable_array realloc
